### PR TITLE
tests: update the CONTRIBUTING.md file using test in local

### PR DESCRIPTION
**Pull request by AhmedElywa**
Updated the CONTRIBUTING.md files on how we will use the test on the local and from fork repos.

### CODE REVIEW

**Review by andrewicarlson — CHANGES_REQUESTED** [review]
I think this PR will need changes, particularly in the `CONTRIBUTING.md` after we decide how to resolve the changes requested in https://github.com/prisma/nexus-prisma/pull/210.

If you want to remove the second bullet:

>- To run E2e tests in your GitHub fork repo actions workflow you will need to add a GitHub actions secrets has an online postgresql url connection with the name `E2E_DB_URL`.

I think this could be merged as is and we can re-address running tests in a fork after https://github.com/prisma/nexus-prisma/pull/210 is resolved.

**Comment by AhmedElywa** [comment]
> I think this PR will need changes, particularly in the `CONTRIBUTING.md` after we decide how to resolve the changes requested in #210.
> 
> If you want to remove the second bullet:
> 
> > * To run E2e tests in your GitHub fork repo actions workflow you will need to add a GitHub actions secrets has an online postgresql url connection with the name `E2E_DB_URL`.
> 
> I think this could be merged as is and we can re-address running tests in a fork after #210 is resolved.

No need to this PR if we not going to merge the #210

**Comment by andrewicarlson** [comment]
>No need to this PR if we not going to merge the https://github.com/prisma/nexus-prisma/pull/210

Do you think the note and configuration for running tests locally could still be useful? I think local tests should be run against a local database, not the one out on Heroku.

**Comment by AhmedElywa** [comment]
> > No need to this PR if we not going to merge the #210
> 
> Do you think the note and configuration for running tests locally could still be useful? I think local tests should be run against a local database, not the one out on Heroku.

I think you have a great idea even if we use Heroku for GitHub it will be better to have a local DB for the local tests it will need some update I will update it and push it.
thanks for your idea

**Comment by jasonkuhrt** [comment]
> I think you have a great idea even if we use Heroku for GitHub it will be better to have a > local DB for the local tests it will need some update I will update it and push it.
> thanks for your idea

Please note you're going to need to figure out how to run Postgres in all OSs on GitHub Actions CI. If you can solve that then great!

**Comment by AhmedElywa** [comment]
> > I think you have a great idea even if we use Heroku for GitHub it will be better to have a > local DB for the local tests it will need some update I will update it and push it.
> > thanks for your idea
> 
> Please note you're going to need to figure out how to run Postgres in all OSs on GitHub Actions CI. If you can solve that then great!

I was saying that we can use docker only for the local tests, not in GitHub actions I already mentioned in #210 that we can't use docker as you said in the CONTRIBUTING file.

I think we can go with the same test flow in every place for now and back to focus on the developer issues for now.

**Pull request closed without merging**
