### PR TITLE
Fixed spellings

### PR DESCRIPTION
**Pull request by kashifnazar**
closes #...

#### TODO

- [x] docs
- [x] tests

### CODE REVIEW

**Review by rostislav-simonik — APPROVED** [review]

**Comment by rostislav-simonik** [comment]
@kashifnazar thx for PR, can you update the snapshot as well, please?

**Comment by kashifnazar** [comment]
Could you please guide me how I can do that?

**Comment by rostislav-simonik** [comment]
@kashifnazar 
```
yarn test:unit --updateSnapshot
```
and commit updated snapshots 

more info here https://jestjs.io/docs/snapshot-testing

**Comment by kashifnazar** [comment]
Thanks @rostislav-simonik. I have updated the snapshot.

**Review by rostislav-simonik — APPROVED** [review]

**Pull request merged**
