### PR TITLE
chore: add timeout for GitHub Actions

### PR DESCRIPTION
**Pull request by Jolg42**
@andrewicarlson the timeout will help avoid a +5h macos runner (which are a scarce resource) like in https://github.com/prisma/nexus-prisma/runs/6783174202?check_suite_focus=true :grimacing:

Feel free to edit the timeouts if needed

### CODE REVIEW

**Comment by AhmedElywa** [comment]
@Jolg42 To pass the test, please upgrade the `tests/e2e/kitchen-sink.test.ts` `ts-node` version to the last one as I did here https://github.com/prisma/nexus-prisma/pull/220/files#diff-b6808e38e36d3598eb12bc75c4e262bbef91d361fed8d7ccea689c0068e6924aR91

**Comment by Jolg42** [comment]
Done! Thanks :)

**Review by jasonkuhrt — APPROVED** [review]
LGTM

**Review by andrewicarlson — APPROVED** [review]

**Pull request merged**
