### PR TITLE
tests: moving the Heroku DB link to GitHub actions secrets.

### PR DESCRIPTION
**Pull request by AhmedElywa**
***We must add the E2E_DB_URL to GitHub actions secrets before running the actions workflow for this PR***

### CODE REVIEW

**Review by jasonkuhrt — APPROVED** [review]
Will this affect the ability for the community to have tests run for their PRs?

**Comment by AhmedElywa** [comment]
> Will this affect the ability for the community to have tests run for their PRs?

The action secret will be added to this repo so anyone who opens a PR from his repo to this one will go successful.

This change will break the tests in the local and forked repos actions.
I added the fixes here #211 another PR as @andrewicarlson asked me to split my code.

to open a PR from [AhmedElywa:tests/db-url](https://github.com/AhmedElywa/nexus-prisma/tree/tests/db-url) to [AhmedElywa:main](https://github.com/AhmedElywa/nexus-prisma/tree/main) I must have the `E2E_DB_URL ` added in my repo as a actions secrets

**Comment by AhmedElywa** [comment]
@andrewicarlson the test has an error because you need to add the E2E_DB_URL to this repo actions secrets 
image

**Comment by jasonkuhrt** [comment]
> The action secret will be added to this repo so anyone who opens a PR from his repo to this one will go successful.

So "yes" it will :/

How are community contributions planned to be merged then?

**Comment by AhmedElywa** [comment]
> > The action secret will be added to this repo so anyone who opens a PR from his repo to this one will go successful.
> 
> 
> 
> So "yes" it will :/
> 
> 
> 
> How are community contributions planned to be merged then?
> 
> 
> 
> 

I said on my comment before if the contributors opened the pr from there repo to this repo as the current pr we talking on it will go successfully 

If they want to merge branches on their repo, they want to create a free PostgreSQL from Heroku to add to their repo actions.

On local, he needs to have a test PostgreSQL on his machine to test with.

As I mentioned before, I have the way to run tests outside this repo actions on the PR #211

**Comment by AhmedElywa** [comment]
And I found that if you have more than one test run simultaneously for more than one PR. The DB connection limit will close the DB.

**Comment by andrewicarlson** [comment]
@AhmedElywa if we move this connection string to GitHub secrets then any forked repository will not be able to issue PR's and run the tests using that [GitHub secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow):

>Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

What are some other ways we could solve this problem? Do we need to use PostgreSQL for this? Would it be possible to start a docker container in the test runner? etc.

**Review by andrewicarlson — CHANGES_REQUESTED** [review]
See comment https://github.com/prisma/nexus-prisma/pull/210#issuecomment-1117485660

**Comment by AhmedElywa** [comment]
> @AhmedElywa if we move this connection string to GitHub secrets then any forked repository will not be able to issue PR's and run the tests using that [GitHub secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow):
> 
> > Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
> 
> What are some other ways we could solve this problem? Do we need to use PostgreSQL for this? Would it be possible to start a docker container in the test runner? etc.

I tested it only on my repo.
about docker @jasonkuhrt have a note into the [CONTRIBUTING](https://github.com/prisma/nexus-prisma/blob/main/CONTRIBUTING.md#remarks) we can not use docker.
I can search for another way and see what I can do.

**Comment by AhmedElywa** [comment]
As we discussed, we can't use this solution `action secrets`, so I will close this PR.

**Pull request closed without merging**
