### PR TITLE
fix(docs): update custom settings example

### LINKED ISSUE #196: nexus_prisma_prefer_config_file warning shows invalid instructions
#### Description

When setting the output directory in schema.prisma we get the following message on `prisma generate`.

```
WARNING: It is preferred to use the Nexus Prisma configuration file to set the output directory.

REASON: Using the Nexus Prisma configuration file gives you access to autocomplete and inline JSDoc documentation.

CONSEQUENCE: Your developer experience may be degraded.

SOLUTION: Create a configuration file in one of the following locations:

→ nexus-prisma.ts
→ nexusPrisma.ts
→ nexus_prisma.ts
→ prisma/nexus-prisma.ts
→ prisma/nexusPrisma.ts
→ prisma/nexus_prisma.ts

Then add the following code:

import { settings } from 'nexus-prisma/generator'

settings.change({
  output: './generated/nexus-prisma'
})

CODE: nexus_prisma_prefer_config_file
```

`settings` does not have a method change. I couldn't find a way to make the configuration file suggestion work.

### PR DESCRIPTION
**Pull request by AhmedElywa**
closes #196

### CODE REVIEW

**Comment by andrewicarlson** [comment]
@AhmedElywa should we write a test for this DX update?

**Review by jasonkuhrt — APPROVED** [review]
Hard to test this I guess because its just docs basically.

**Comment by AhmedElywa** [comment]
> @AhmedElywa should we write a test for this DX update?

Test what? 
I only changed a docs how we call the custom settings function no need for test here you can merge it.👍

**Comment by andrewicarlson** [comment]
Agreed on the docs change, but there is a CLI output that we changed. (src/cli/nexus-prisma.ts)

@AhmedElywa  looks like the test on MacOS 16 is failing

**Comment by AhmedElywa** [comment]
> Agreed on the docs change, but there is a CLI output that we changed. (src/cli/nexus-prisma.ts)
> 
> @AhmedElywa looks like the test on MacOS 16 is failing

I can’t do anything about the MacOS issue the time in snap in ms but the time In the test in seconds that’s why it’s failing

**Comment by AhmedElywa** [comment]
@andrewicarlson what is the purpose of the testing here?

**Comment by jasonkuhrt** [comment]
> I can’t do anything about the MacOS issue the time in snap in ms but the time In the test in seconds that’s why it’s failing

Please just update the regex string replace to not assume `ms` but account for `s` OR `ms` units. It'll require a snapshot update with new replacement of e.g. `<unit>`.

**Comment by AhmedElywa** [comment]
> > I can’t do anything about the MacOS issue the time in snap in ms but the time In the test in seconds that’s why it’s failing
> 
> Please just update the regex string replace to not assume `ms` but account for `s` OR `ms` units. It'll require a snapshot update with new replacement of e.g. `<unit>`.

Thanks for your help I opened new PR #217 for that fix Please do a review

**Review by jasonkuhrt — APPROVED** [review]
LGTM

**Pull request merged**
